services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: my-api-shop
    ports:
      - 5000:5000
    networks:
      - myNetwork
    restart: always

  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: my-client-shop
    ports:
      - 3000:3000
    networks:
      - myNetwork
    restart: always
    depends_on:
      - server

networks:
  myNetwork:
    driver: bridge
